/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue_Controller;

import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static Modele.DAO_Connection.data;
import static Modele.Sousprogrammes.println;

/**
 *
 * @author lilia
 */
public class Chargement extends javax.swing.JFrame {

    /**
     * Creates new form Chargement
     */
    public Chargement() {
        initComponents();
        Icon i= new ImageIcon(this.getClass().getResource("KIDSLAND (1).gif"));
        l1.setIcon(i);
        setLocationRelativeTo(null);
       
        getContentPane().setBackground(Color.WHITE);
         setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);/// il ne se passe rien quand on la ferme
       
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loading = new javax.swing.JProgressBar();
        pourcentage = new javax.swing.JLabel();
        l = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        loading.setBackground(new java.awt.Color(255, 255, 255));
        loading.setForeground(new java.awt.Color(0, 153, 255));
        loading.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        pourcentage.setFont(new java.awt.Font("Verdana", 2, 12)); // NOI18N
        pourcentage.setForeground(new java.awt.Color(0, 153, 255));
        pourcentage.setText("100%");

        l.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        l.setForeground(new java.awt.Color(0, 153, 255));
        l.setText("Loading...");

        l1.setBackground(new java.awt.Color(255, 255, 255));
        l1.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        l1.setForeground(new java.awt.Color(0, 153, 255));
        l1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pourcentage)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(l1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(loading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addComponent(l)
                .addContainerGap(317, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(l)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loading, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(pourcentage)
                .addGap(38, 38, 38))
        );

        setSize(new java.awt.Dimension(703, 443));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void charg()
    {
 
          
            for(int i=0;i<=100;i++)
        {
        try {
                 
                Thread.sleep(30);
                } catch (InterruptedException ex) {
                    println(ex.getMessage());
                }
                
            pourcentage.setText(Integer.toString(i)+"%");
            loading.setValue(i);
               
        }
            
       
           
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel l;
    private javax.swing.JLabel l1;
    public static javax.swing.JProgressBar loading;
    public static javax.swing.JLabel pourcentage;
    // End of variables declaration//GEN-END:variables
}
