/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projet.Ecran;

import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static projet.Serveur.data;
import static projet.Sousprogrammes.println;

/**
 *
 * @author lilia
 */
public class Chargement extends javax.swing.JFrame {

    /**
     * Creates new form Chargement
     */
    public Chargement() {
        initComponents();
        setLocationRelativeTo(null);
       
        getContentPane().setBackground(Color.WHITE);
        
       
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loading = new javax.swing.JProgressBar();
        pourcentage = new javax.swing.JLabel();
        l = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        loading.setBackground(new java.awt.Color(255, 255, 255));
        loading.setForeground(new java.awt.Color(0, 153, 255));
        loading.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        pourcentage.setFont(new java.awt.Font("Verdana", 2, 12)); // NOI18N
        pourcentage.setForeground(new java.awt.Color(0, 153, 255));
        pourcentage.setText("100%");

        l.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        l.setForeground(new java.awt.Color(0, 153, 255));
        l.setText("Loading...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(loading, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(l)
                        .addGap(183, 183, 183))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(pourcentage)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(l)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loading, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(pourcentage)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(463, 164));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void charg()
    {
        
       
          
            for(int i=0;i<=100;i++)
        {
        try {
                 
                    Thread.sleep(30);
                } catch (InterruptedException ex) {
                    println(ex.getMessage());
                }
                
            pourcentage.setText(Integer.toString(i)+"%");
            loading.setValue(i);
               
        }
            
       
           
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel l;
    public static javax.swing.JProgressBar loading;
    public static javax.swing.JLabel pourcentage;
    // End of variables declaration//GEN-END:variables
}
