/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projet.Ecran;

import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import projet.Ride;

/**
 *
 * @author lilia
 */
public class ChooseRide extends javax.swing.JFrame implements MouseListener{

    /**
     * Creates new form jFrame4
     */
    public ChooseRide() {
        initComponents();
        getContentPane().setBackground(Color.WHITE);
        ride7.addMouseListener(this);
        ride2.addMouseListener(this);
        ride3.addMouseListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ride1 = new javax.swing.JLabel();
        ride2 = new javax.swing.JLabel();
        ride3 = new javax.swing.JLabel();
        ride7 = new javax.swing.JLabel();
        ride8 = new javax.swing.JLabel();
        ride9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setText("Choose your ride");

        ride1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ride1.setForeground(new java.awt.Color(109, 133, 250));
        ride1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projet/ImageFrame/Capture1.PNG"))); // NOI18N
        ride1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ride1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        ride2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ride2.setForeground(new java.awt.Color(109, 133, 250));
        ride2.setText("The Boat");
        ride2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ride2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        ride3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ride3.setForeground(new java.awt.Color(109, 133, 250));
        ride3.setText("The Flying Chairs");
        ride3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ride3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        ride7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ride7.setForeground(new java.awt.Color(109, 133, 250));
        ride7.setText("Roller Coaster");
        ride7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ride7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        ride8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ride8.setForeground(new java.awt.Color(109, 133, 250));
        ride8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projet/ImageFrame/Capture3.PNG"))); // NOI18N
        ride8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ride8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        ride9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ride9.setForeground(new java.awt.Color(109, 133, 250));
        ride9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projet/ImageFrame/Capture2.PNG"))); // NOI18N
        ride9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ride9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(ride7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ride2)
                .addGap(246, 246, 246))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(ride1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(ride8)
                .addGap(42, 42, 42))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addComponent(ride9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(429, 429, 429)
                        .addComponent(ride3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(419, 419, 419)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ride7)
                    .addComponent(ride2))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ride1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ride8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(ride3)
                .addGap(18, 18, 18)
                .addComponent(ride9)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel ride1;
    private javax.swing.JLabel ride2;
    private javax.swing.JLabel ride3;
    private javax.swing.JLabel ride7;
    private javax.swing.JLabel ride8;
    private javax.swing.JLabel ride9;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent me) {
        
        if(me.getSource()==ride7)
        {
            ChooseDate j=new ChooseDate();
            j.setVisible(true);
            setVisible(false);
            
        }
        else if(me.getSource()==ride2)
        {
            ChooseDate j=new ChooseDate();
            j.setVisible(true);
            setVisible(false);
        }
        else if(me.getSource()==ride3)
        {
            ChooseDate j=new ChooseDate();
            j.setVisible(true);
            setVisible(false);
        }
        
        
    }

    @Override
    public void mousePressed(MouseEvent me) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseReleased(MouseEvent me) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseEntered(MouseEvent me) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseExited(MouseEvent me) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
