/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projet.Ecran;

import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import static projet.Serveur.data;
import static projet.Sousprogrammes.println;


/**
 *
 * @author lilia
 */
public class ChooseRide extends javax.swing.JFrame implements MouseListener{

    /**
     * Creates new form jFrame4
     */
    public ChooseRide(double d) {
        initComponents();
        getContentPane().setBackground(Color.WHITE);
        ride3.addMouseListener(this);
        ride1.addMouseListener(this);
        ride2.addMouseListener(this);
        ride4.addMouseListener(this);
        ride6.addMouseListener(this);
        photo.addMouseListener(this);
        this.discount_child=d;
        setLocationRelativeTo(null);
        addWindowListener(new WindowAdapter(){///close serv if close jframe
        public void windowClosing(WindowEvent e){data.deconnection();}});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        ride1 = new javax.swing.JLabel();
        ride2 = new javax.swing.JLabel();
        ride3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ride4 = new javax.swing.JLabel();
        ride5 = new javax.swing.JLabel();
        ride6 = new javax.swing.JLabel();
        menue = new javax.swing.JButton();
        photo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Choose your ride");

        ride1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ride1.setForeground(new java.awt.Color(51, 51, 51));
        ride1.setText("The Boat");
        ride1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ride1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        ride2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ride2.setText("The Flying Chairs");
        ride2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ride2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        ride3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ride3.setText("Roller Coaster");
        ride3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ride3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel2.setBackground(new java.awt.Color(215, 215, 235));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projet/ImageFrame/peinture-pour-artiste-bleu-ciel.jpg"))); // NOI18N

        jLabel3.setBackground(new java.awt.Color(215, 215, 235));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projet/ImageFrame/peinture-pour-artiste-bleu-ciel.jpg"))); // NOI18N

        ride4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ride4.setText("The Flying Chairs");
        ride4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ride4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        ride5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ride5.setText("The Flying Chairs");
        ride5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ride5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        ride6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ride6.setText("The Flying Chairs");
        ride6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ride6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projet/ImageFrame/bouton menu.PNG"))); // NOI18N
        menue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menueActionPerformed(evt);
            }
        });

        photo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(244, 244, 244)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ride5)
                                    .addComponent(ride6)
                                    .addComponent(ride4)
                                    .addComponent(ride3)
                                    .addComponent(ride1)
                                    .addComponent(ride2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(photo, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(92, 92, 92))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(352, 352, 352)
                        .addComponent(menue, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(photo, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(ride1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ride2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ride3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ride4)
                        .addGap(20, 20, 20)
                        .addComponent(ride5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ride6)))
                .addGap(67, 67, 67)
                .addComponent(menue, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menueActionPerformed
        // TODO add your handling code here:
        MainMenu j=new MainMenu();
        j.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_menueActionPerformed


    private final double discount_child;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JButton menue;
    private javax.swing.JLabel photo;
    private javax.swing.JLabel ride1;
    private javax.swing.JLabel ride2;
    private javax.swing.JLabel ride3;
    private javax.swing.JLabel ride4;
    private javax.swing.JLabel ride5;
    private javax.swing.JLabel ride6;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent me) {
        if(me.getSource()==photo)
        {
            ChooseDate j=new ChooseDate(discount_child);
            j.setVisible(true);
            setVisible(false);
        }
        String imgUrl_ride3="build/classes/projet/ImageFrame/Capture1.PNG";
        String imgUrl_ride1="build/classes/projet/ImageFrame/Capture3.PNG";
        String imgUrl_ride2="build/classes/projet/ImageFrame/Capture2.PNG";

        if(me.getSource()==ride1)
        {
            Icon icone=new ImageIcon(imgUrl_ride1);
            photo.setIcon(icone);

        }
        else if(me.getSource()==ride2)
        {
            Icon icone=new ImageIcon(imgUrl_ride2);
            photo.setIcon(icone);

        }
        else if(me.getSource()==ride3)
        {
            Icon icone=new ImageIcon(imgUrl_ride3);
            photo.setIcon(icone);
        }
        else if(me.getSource()==ride4)
        {
            //Icon icone=new ImageIcon(imgUrl_ride4);
            //photo.setIcon(icone);

        }
        else if(me.getSource()==ride5)
        {
            //Icon icone=new ImageIcon(imgUrl_ride5);
            //photo.setIcon(icone);

        }
        else if(me.getSource()==ride6)
        {
            //Icon icone=new ImageIcon(imgUrl_ride6);
            //photo.setIcon(icone);
        }
    }

    @Override
    public void mousePressed(MouseEvent me) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseReleased(MouseEvent me) {
        
    }

    @Override
    public void mouseEntered(MouseEvent me) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseExited(MouseEvent me) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
